### ISSUE TITLE
Preset mode as entities

### ISSUE THREAD

**Issue by CrashOverride-Git** [kongo09/philips-airpurifier-coap#21]
Hello, is it possible to automatically create the entities for the _each_ preset mode?

edit, added _each_

**Comment by kongo09** [comment]
I'm not entirely sure if I understand what you mean?

**Comment by CrashOverride-Git** [comment]
I mean, to have the ability to change the mode instead having the preset_mode and select the mode from a submenu

Something like this: 
If I want to power on the device in auto I can push the second last button (pressed and on in the example below), or if I want to power off the device I can push the first button and so on.

I did it in javascript but having the entitities directly from the component could be nice

![image](https://user-images.githubusercontent.com/82328866/166728648-89d63301-b429-440d-ad21-0688a7923b34.png)

this is my js I used with the betaboon component


```
class AirPurifierCard extends Polymer.Element {

    static get template() {
        return Polymer.html`
            <style is="custom-style" include="iron-flex iron-flex-alignment"></style>
            <style>
                :host {
                    line-height: 1.5;
                }
                .grp_cmd_preset {
                    padding: 0 10px;
                    margin: 10px 0;
                }
                .cmd_preset {
                    float: right;
                    margin: 15px 0 0 10px;                    
                }

                .cmd_preset_icon {
                    padding: 8px 4px;
                    width: auto;
                    height: auto;
                }
        
                ha-entity-toggle {
                    margin-left: 10px;
                }
            </style>

             <div class='grid justified layout grp_cmd_preset' on-click="stopPropagation">

                <mwc-button
                    class='cmd_preset'
                    raised noink name="sleep"
                    on-click='setPreset'
                    disabled='[[_is_Sleep]]'><ha-icon icon="mdi:power-sleep" class="cmd_preset_icon"></ha-icon></mwc-button>

                <mwc-button
                    class='cmd_preset'
                    raised noink name="auto"
                    on-click='setPreset'
                    disabled='[[_is_Auto]]'><ha-icon icon="mdi:fan-auto" class="cmd_preset_icon"></ha-icon></mwc-button>       

                <mwc-button
                    class='cmd_preset'
                    raised noink name="turbo"
                    on-click='setPreset'
                    disabled='[[_is_Turbo]]'><ha-icon icon="mdi:fan-speed-3" class="cmd_preset_icon"></ha-icon></mwc-button>

                <mwc-button
                    class='cmd_preset'
                    raised noink name="2"
                    on-click='setPreset'
                    disabled='[[_is_Set2]]'><ha-icon icon="mdi:fan-speed-2" class="cmd_preset_icon"></ha-icon></mwc-button>                    

                <mwc-button
                    class='cmd_preset'
                    raised noink name="1"
                    on-click='setPreset'
                    disabled='[[_is_Set1]]'><ha-icon icon="mdi:fan-speed-1" class="cmd_preset_icon"></ha-icon></mwc-button>

                <mwc-button
                    class='cmd_preset'
                    raised noink name="off"
                    on-click='setOff'
                    disabled='[[_is_OFF]]'><ha-icon icon="mdi:fan-off" class="cmd_preset_icon"></ha-icon></mwc-button>    


            </div>

        `;
    }

    static get properties() {
        return {
            hass: {
                type: Object,
                observer: 'hassChanged'
            },
            _config: Object,
            _stateObj: Object,
            _is_OFF: Boolean,
            _is_Set1: Boolean,
            _is_Set2: Boolean,
            _is_Auto: Boolean,
            _is_Sleep: Boolean,
            _is_Turbo: Boolean
        }
    }

    setConfig(config) {
        this._config = config;
    }


    hassChanged(hass) {

        const config = this._config;
        const stateObj = hass.states[config.entity];

        let mode;
        if (stateObj && stateObj.attributes) {
            mode = stateObj.attributes.preset_mode;
        }

        var off = stateObj.state != 'on';
        

        this.setProperties({
            _stateObj: stateObj,
            _is_Set1: mode === '1',
            _is_Set2: mode === '2',
            _is_Auto: mode === 'auto',
            _is_Sleep: mode === 'sleep',
            _is_Turbo: mode === 'turbo',
            _is_OFF: mode == null
        });

        //console.log(_is_OFF);
        //console.log(off);
    }

    stopPropagation(e) {
        e.stopPropagation();
    }

    setOff(e) {
        this.hass.callService('fan', 'turn_off', {
            entity_id: this._config.entity
         });
    }


    setPreset(e) {

        const valore = e.currentTarget.getAttribute('name');
        //console.log(valore);
        this.hass.callService('fan', 'set_preset_mode', {
           entity_id: this._config.entity, preset_mode: valore
        });
    }

}

customElements.define('air-purifier-card', AirPurifierCard);

```

**Comment by kongo09** [comment]
Oh, you can already do that with services

**Comment by kongo09** [comment]
use [custom:button-card](https://github.com/custom-cards/button-card)

![image](https://user-images.githubusercontent.com/640121/166835534-8e107f89-2d56-4d71-ae21-1ec83f71bc83.png)


```yaml
type: horizontal-stack
cards:
  - type: custom:button-card
    entity: fan.schlafzimmer
    show_name: false
    icon: mdi:fan-off
    tap_action:
      action: call-service
      service: fan.turn_off
      service_data:
        entity_id: fan.schlafzimmer
    styles:
      card:
        - background-color: blue
    state:
      - value: 'off'
        styles:
          icon:
            - color: grey
          card:
            - background-color: null
  - type: custom:button-card
    icon: mdi:fan-speed-1
    tap_action:
      action: call-service
      service: fan.set_preset_mode
      service_data:
        entity_id: fan.schlafzimmer
        preset_mode: speed 1
    styles:
      card:
        - background-color: blue
    state:
      - operator: template
        value: >-
          [[[ return states["fan.schlafzimmer"].attributes.preset_mode == "speed
          1" ]]]
        styles:
          icon:
            - color: grey
          card:
            - background-color: null
  - type: custom:button-card
    icon: mdi:fan-speed-2
    tap_action:
      action: call-service
      service: fan.set_preset_mode
      service_data:
        entity_id: fan.schlafzimmer
        preset_mode: speed 2
    styles:
      card:
        - background-color: blue
    state:
      - operator: template
        value: >-
          [[[ return states["fan.schlafzimmer"].attributes.preset_mode == "speed
          2" ]]]
        styles:
          icon:
            - color: grey
          card:
            - background-color: null
  - type: custom:button-card
    icon: mdi:fan-speed-3
    tap_action:
      action: call-service
      service: fan.set_preset_mode
      service_data:
        entity_id: fan.schlafzimmer
        preset_mode: speed 3
    styles:
      card:
        - background-color: blue
    state:
      - operator: template
        value: >-
          [[[ return states["fan.schlafzimmer"].attributes.preset_mode == "speed
          3" ]]]
        styles:
          icon:
            - color: grey
          card:
            - background-color: null
  - type: custom:button-card
    icon: mdi:fan-auto
    tap_action:
      action: call-service
      service: fan.set_preset_mode
      service_data:
        entity_id: fan.schlafzimmer
        preset_mode: auto
    styles:
      card:
        - background-color: blue
    state:
      - operator: template
        value: >-
          [[[ return states["fan.schlafzimmer"].attributes.preset_mode == "auto"
          ]]]
        styles:
          icon:
            - color: grey
          card:
            - background-color: null
  - type: custom:button-card
    icon: mdi:power-sleep
    tap_action:
      action: call-service
      service: fan.set_preset_mode
      service_data:
        entity_id: fan.schlafzimmer
        preset_mode: night
    styles:
      card:
        - background-color: blue
    state:
      - operator: template
        value: >-
          [[[ return states["fan.schlafzimmer"].attributes.preset_mode ==
          "night" ]]]
        styles:
          icon:
            - color: grey
          card:
            - background-color: null
```
