### ISSUE TITLE
Support for selecting an operating mode in an automation

### ISSUE THREAD

**Issue by kaischmerer** [kongo09/philips-airpurifier-coap#215]
Maybe I have overlooked something, but I cannot select an operating mode in an automation, but it is displayed on the device page. 

![HA-Philips-AC3421-Choosing-Mode-in-Automation](https://github.com/user-attachments/assets/a462b063-d64f-4a3d-b153-95a8418bd4db)
![HA-Philips-AC3421-Choosing-Mode-in-Automation-2](https://github.com/user-attachments/assets/7c3bb947-e306-49ef-bbd1-67299dc0ef0e)
![HA-Philips-AC3421-Choosing-Mode-in-Automation-4](https://github.com/user-attachments/assets/595ce75d-01ff-4238-9a82-677e4e6d38a4)

**Comment by kongo09** [comment]
This shouldn't be a problem at all. I've just built an automation in the UI to switch my air purifier to `Night` mode at 22:00. In the resulting yaml it looks like this:

```yaml
alias: Good Night
description: Switch preset mode to Night at 22:00
triggers:
  - trigger: time
    at: "22:00:00"
conditions: []
actions:
  - action: fan.set_preset_mode
    metadata: {}
    data:
      preset_mode: Night
    target:
      device_id: 5f1b117804bd33c93d469ce768ccbc40
mode: single
```
