### ISSUE TITLE
switch mode and power in separate calls for AC1214/10

### ISSUE THREAD

**Issue by kongo09** [kongo09/philips-airpurifier-coap#23]

**Comment by kongo09** [comment]
please try v0.10.1-beta1214.1

@lwd1991 can you please try and see if this fixes this particular problem?

**Comment by lwd1991** [comment]
Installed: v0.10.1-beta1214.1
Unfortunately, it does not fix this particular problem.

- When power off: selecting AUTO, ALLERGEN or NIGHT powers on the device but does not switch to correct mode (still in latest mode before power off).
- When power off: selecting Speed 1/2/3/t does switch selected speed (viewed in Phillips home iOS app), but does not switch on device.
- When power on: Switching between 1/2/3/t works.
- When power on: Switching modes doesn't work (including switching to and from manual speed mode).

After removing `PHILIPS_POWER: "1", ` on all lines for AC1214:
- When power off: selecting modes AUTO, ALLERGEN or NIGHT (viewed in Phillips home iOS app) is possible, but obviously does not start the device. 
- When power off: selecting Speed 1/2/3/t does **NOT** switch selected speed or start device (viewed in Phillips home iOS app). 
- When power on: Switching between Speed 1/3/t and ALLERGEN works. Switching from Speed 2 to ALLERGEN does work. (not sure if this is new issue or I missed it last time I checked)
- When power on: Switching between Speed 2/3/t and AUTO works. Switching from Speed 1 to AUTO does work. (not sure if this is new issue or I missed it last time I checked)
- When power on: Switching between AUTO, ALLERGEN or NIGHT works.
- When power on: Switching between AUTO/NIGHT to Speed 1/2/3/t does not work.

NOTE:
- When I leave `PHILIPS_POWER: "1", ` for speed 1/2/3/t it makes no difference compared to deleting.

I havent been able to set up `aioairctrl` yet since Ive been abroad lately, and will be frequently next couple of months.
Anyway hope I could still be of some help. Thanks again!

**Comment by kongo09** [comment]
Thanks for the feedback. I'm a bit irritated that you say your remove "PHILIPS_POWER" as that should have been removed in the AC1214 code already. That was the whole point of the beta. Are your sure the update to the beta worked for you?

The file `philips.py` should have the following code for the AC1214 now:

```yaml
class PhilipsAC1214(PhilipsGenericCoAPFan):
    # the AC1214 doesn't seem to like a power on call when the mode or speed is set,
    # so this needs to be handled separately
    SERIALIZE_POWER_CALL = True
    AVAILABLE_PRESET_MODES = {
        PRESET_MODE_AUTO: {PHILIPS_MODE: "P"},
        PRESET_MODE_ALLERGEN: {PHILIPS_MODE: "A"},
        # make speeds available as preset
        PRESET_MODE_NIGHT: {PHILIPS_MODE: "N"},
        SPEED_1: {PHILIPS_MODE: "M", PHILIPS_SPEED: "1"},
        SPEED_2: {PHILIPS_MODE: "M", PHILIPS_SPEED: "2"},
        SPEED_3: {PHILIPS_MODE: "M", PHILIPS_SPEED: "3"},
        PRESET_MODE_TURBO: {PHILIPS_MODE: "M", PHILIPS_SPEED: "t"},
    }
    AVAILABLE_SPEEDS = {
        PRESET_MODE_NIGHT: {PHILIPS_MODE: "N"},
        SPEED_1: {PHILIPS_MODE: "M", PHILIPS_SPEED: "1"},
        SPEED_2: { PHILIPS_MODE: "M", PHILIPS_SPEED: "2"},
        SPEED_3: {PHILIPS_MODE: "M", PHILIPS_SPEED: "3"},
        PRESET_MODE_TURBO: {PHILIPS_MODE: "M", PHILIPS_SPEED: "t"},
    }
    AVAILABLE_SWITCHES = [PHILIPS_CHILD_LOCK]
```
