### ISSUE TITLE
model AC3055 fails to connect

### ISSUE THREAD

**Issue by eugenedani** [kongo09/philips-airpurifier-coap#31]
Thank you for adding 3055 to the list but unfortunately it still does not work.  I cannot add it by device IP address.
The error message:

Logger: coap
Source: /usr/local/lib/python3.9/site-packages/aiocoap/transports/udp6.py:525
First occurred: 21:05:10 (2 occurrences)
Last logged: 21:09:44

Connection loss was not expected.

**Comment by kongo09** [comment]
Can you please enable the debug log for `aioairctrl` and `philips_airpurifier_coap` in `configuration.yaml`?

```yaml
logger:
  default: error
  logs:
    custom_components.philips_airpurifier_coap: debug
    aioairctrl: debug
```

and share the result. Also, please unplug and replug your Philips device and restart HA before you try to add it. The Philips devices have a connectivity problem.
